api_key: 070015acb35d
api_secret: 1ebd13d2a06a44456961489157de89c8ff9263880d148cb2
ws_url: ws://livekit:7880

redis:
  address: redis:6379

rtmp_port: 1935
whip_port: 8088

cpu_cost:
  rtmp_cpu_cost: 2
  whip_cpu_cost: 2
  whip_bypass_transcoding_cpu_cost: 0.1
  url_cpu_cost: 2

logging:
  level: info
