import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    'help',
    'faq',
    {
      type: 'category',
      label: "Developers",
      link: {
        type: "generated-index",
        description: "Building with PLG Voice"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers',
        }
      ]
    },
    {
      type: 'category',
      label: "Developing PLG Voice",
      link: {
        type: "generated-index",
        description: "Building PLG Voice"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developing',
        },
        {
          type: 'link',
          label: "for Web",
          href: "https://github.com/Leonid1095/PLGames-Voice/tree/main/client"
        },
        {
          type: 'link',
          label: "for Android",
          href: "https://github.com/Leonid1095/PLGames-Voice"
        }
      ]
    }
  ],
};

export default sidebars;
